alliancecrafts/urls.py
from django.urls import path
from . import views

appname = 'alliancecrafts'
urlpatterns = [
    path('all/', views.all, name='all'),
    path('botindex/', views.botindex, name='botindex'),
    path('<int:request_id>/', views.getstatus, name='getstatus'),
    path('push/<int:request_id>/', views.update_status, name='update_status'),
    path('', views.addcraft, name='addcraft')
]

craftquests/urls.py
from django.urls import path
from . import views

appname = 'craftquests'
urlpatterns = [
    path('all/', views.all, name='all'),
    path('botindex/', views.botindex, name='botindex'),
    path('<int:request_id>/', views.getstatus, name='getstatus'),
    path('push/<int:request_id>/', views.update_status, name='update_status'),
    path('', views.addcraft, name='addcraft')
]

crowcalc/urls.py
from django.urls import path

from . import views

appname = 'crowcalc'
urlpatterns = [
    path('', views.search, name='index'),
    path('search/', views.search, name='search')
]

lionforge/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)

urlpatterns = [
    path('craftquests/', include('craftquests.urls')),
    path('alliancecrafts/', include('alliancecrafts.urls')),
    # path('crowcalc/', include('crowcalc.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^favicon\.ico$', favicon_view),
    path('', TemplateView.as_view(template_name='index.html')),
    path('recruitment/', TemplateView.as_view(template_name='recruitment.html')),
]

alliancecrafts/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class CraftingDiscipline(models.TextChoices):
    ALC = 'ALC', _('Alchemy')
    ARM = 'ARM', _('Armorsmithing')
    BKS = 'BKS', _('Blacksmithing')
    CKG = 'CKG', _('Cooking')
    JWL = 'JWL', _('Jewelcrafting')
    LTW = 'LTW', _('Leatherworking')
    NEC = 'NEC', _('Necromancy')
    RUN = 'RUN', _('Runemaking')
    STO = 'STO', _('Stonemasonry')
    WPN = 'WPN', _('Weaponsmithing')
    WOO = 'WOO', _('Woodworking')

class Rarity(models.TextChoices):
    C = 'C', _('Common')
    U = 'U', _('Uncommon')
    R = 'R', _('Rare')
    E = 'E', _('Epic')
    L = 'L', _('Legendary')

class ActiveCompleted(models.IntegerChoices):
    Active = 1
    Complete = 0

class ResourceProvided(models.IntegerChoices):
    Yes = 1
    No = 0
    
class CraftingRequest(models.Model):
    requester = models.CharField(max_length=50)
    item_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Requested time')
    
    quantity = models.IntegerField()
    crafting_discipline = models.CharField(max_length=3, choices=CraftingDiscipline.choices)
    special_instruction = models.TextField(null=True, blank=True)
    stats = models.TextField(default="Crafter's choice", null=True, blank=True)
    rarity = models.CharField(max_length=3, choices=Rarity.choices)
    resource_provided = models.IntegerField(choices=ResourceProvided.choices)
    custom_name = models.CharField(max_length=200, null=True, blank=True)

    status = models.IntegerField(choices=ActiveCompleted.choices, default=1)
    crafter = models.CharField(max_length=50, null=True, blank=True)
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return f'{self.requester}[{self.crafting_discipline}]: {self.item_name}'

    def __iter__(self):
        field_names = [f.name for f in self._meta.get_fields()]
        for field_name in field_names:
            value = getattr(self, field_name, None)
            yield (field_name, value)

craftquests/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class CraftingDiscipline(models.TextChoices):
    ALC = 'ALC', _('Alchemy')
    ARM = 'ARM', _('Armorsmithing')
    BKS = 'BKS', _('Blacksmithing')
    CKG = 'CKG', _('Cooking')
    JWL = 'JWL', _('Jewelcrafting')
    LTW = 'LTW', _('Leatherworking')
    NEC = 'NEC', _('Necromancy')
    RUN = 'RUN', _('Runemaking')
    STO = 'STO', _('Stonemasonry')
    WPN = 'WPN', _('Weaponsmithing')
    WOO = 'WOO', _('Woodworking')

class Rarity(models.TextChoices):
    C = 'C', _('Common')
    U = 'U', _('Uncommon')
    R = 'R', _('Rare')
    E = 'E', _('Epic')
    L = 'L', _('Legendary')

class ActiveCompleted(models.IntegerChoices):
    Active = 1
    Complete = 0

class ResourceProvided(models.IntegerChoices):
    Yes = 1
    No = 0
    
class CraftingRequest(models.Model):
    requester = models.CharField(max_length=50)
    item_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Requested time')
    
    quantity = models.IntegerField()
    crafting_discipline = models.CharField(max_length=3, choices=CraftingDiscipline.choices)
    special_instruction = models.TextField(null=True, blank=True)
    stats = models.TextField(default="Crafter's choice", null=True, blank=True)
    rarity = models.CharField(max_length=3, choices=Rarity.choices)
    resource_provided = models.IntegerField(choices=ResourceProvided.choices)
    custom_name = models.CharField(max_length=200, null=True, blank=True)

    status = models.IntegerField(choices=ActiveCompleted.choices, default=1)
    crafter = models.CharField(max_length=50, null=True, blank=True)
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return f'{self.requester}[{self.crafting_discipline}]: {self.item_name}'

    def __iter__(self):
        field_names = [f.name for f in self._meta.get_fields()]
        for field_name in field_names:
            value = getattr(self, field_name, None)
            yield (field_name, value)

alliancecrafts/views.py
from re import L
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.http import JsonResponse

from .models import CraftingRequest
import requests

def all(request):
    latest_req_list = CraftingRequest.objects.order_by('pub_date')
    active_req = latest_req_list.filter(status=1)
    
    unclaimed_req = [item for item in active_req if (item.crafter is None or item.crafter == "")]
    claimed_req = [item for item in active_req if (type(item.crafter) == str and len(item.crafter) > 0)]

    context = {'claimed_req': claimed_req,
               'unclaimed_req': unclaimed_req,
               'completed_req': latest_req_list.filter(status=0)} 

    return render(request, 'alliancecrafts/all.html', context)

def _assign_fields(item_list):
    dict_output = {}

    for item in item_list:
        dict_output[item.id] = {}

        for field, val in item:
            dict_output[item.id][field] = val

    return dict_output

def botindex(request):
    latest_req_list = CraftingRequest.objects.order_by('pub_date')
    active_req = latest_req_list.filter(status=1)   

    unclaimed_req = [item for item in active_req if (item.crafter is None or item.crafter == "")]
    claimed_req = [item for item in active_req if (type(item.crafter) == str and len(item.crafter) > 0)]

    completed_req = latest_req_list.filter(status=0)

    context = {'claimed_req': _assign_fields(claimed_req),
                'unclaimed_req': _assign_fields(unclaimed_req),
                'completed_req': _assign_fields(completed_req)}

    return JsonResponse(context)

@csrf_exempt
def update_status(request, request_id):
    if request.method == "POST":
        req = get_object_or_404(CraftingRequest, pk=request_id)
        return HttpResponse(req.item_name)
        req.status = request.POST['status_update']
        req.crafter = request.POST['crafter']
        req.save()

        return HttpResponse('Success')
    else:
        return HttpResponse('No')

def getstatus(request, request_id):
    req = get_object_or_404(CraftingRequest, pk=request_id)
    return render(request, 'alliancecrafts/detail.html', {'req': req})

def addcraft(request):
    try:
        new_craftingrequest = CraftingRequest(
            requester=request.POST['requester'],
            item_name=request.POST['item_name'],
            custom_name=request.POST['custom_name'],
            crafting_discipline=request.POST['crafting_discipline'],
            stats=request.POST['stats'],
            quantity=request.POST['quantity'],
            special_instruction=request.POST['special_instruction'],
            status=1,
            rarity=request.POST['rarity'],
            resource_provided=int(request.POST['resource_provided']),
            pub_date=timezone.now()
        )
        new_craftingrequest.save()
        return HttpResponseRedirect('/alliancecrafts/')
        
    except MultiValueDictKeyError as e:
        return render(request, 'alliancecrafts/addcraft.html', {})

craftquests/views.py
from re import L
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.http import JsonResponse

from .models import CraftingRequest
import requests

def all(request):
    latest_req_list = CraftingRequest.objects.order_by('pub_date')
    active_req = latest_req_list.filter(status=1)
    
    unclaimed_req = [item for item in active_req if (item.crafter is None or item.crafter == "")]
    claimed_req = [item for item in active_req if (type(item.crafter) == str and len(item.crafter) > 0)]

    context = {'claimed_req': claimed_req,
               'unclaimed_req': unclaimed_req,
               'completed_req': latest_req_list.filter(status=0)} 

    return render(request, 'craftquests/all.html', context)

def _assign_fields(item_list):
    dict_output = {}

    for item in item_list:
        dict_output[item.id] = {}

        for field, val in item:
            dict_output[item.id][field] = val

    return dict_output

def botindex(request):
    latest_req_list = CraftingRequest.objects.order_by('pub_date')
    active_req = latest_req_list.filter(status=1)   

    unclaimed_req = [item for item in active_req if (item.crafter is None or item.crafter == "")]
    claimed_req = [item for item in active_req if (type(item.crafter) == str and len(item.crafter) > 0)]

    completed_req = latest_req_list.filter(status=0)

    context = {'claimed_req': _assign_fields(claimed_req),
                'unclaimed_req': _assign_fields(unclaimed_req),
                'completed_req': _assign_fields(completed_req)}

    return JsonResponse(context)

@csrf_exempt
def update_status(request, request_id):
    if request.method == "POST":
        req = get_object_or_404(CraftingRequest, pk=request_id)
        return HttpResponse(req.item_name)
        req.status = request.POST['status_update']
        req.crafter = request.POST['crafter']
        req.save()

        return HttpResponse('Success')
    else:
        return HttpResponse('No')

def getstatus(request, request_id):
    req = get_object_or_404(CraftingRequest, pk=request_id)
    return render(request, 'craftquests/detail.html', {'req': req})

def addcraft(request):
    try:
        new_craftingrequest = CraftingRequest(
            requester=request.POST['requester'],
            item_name=request.POST['item_name'],
            custom_name=request.POST['custom_name'],
            crafting_discipline=request.POST['crafting_discipline'],
            stats=request.POST['stats'],
            quantity=request.POST['quantity'],
            special_instruction=request.POST['special_instruction'],
            status=1,
            rarity=request.POST['rarity'],
            resource_provided=int(request.POST['resource_provided']),
            pub_date=timezone.now()
        )
        new_craftingrequest.save()
        return HttpResponseRedirect('/craftquests/')
        
    except MultiValueDictKeyError as e:
        return render(request, 'craftquests/addcraft.html', {})

craftquests/templates/alliancecrafts/addcraft.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
		<title>[-LFG-] Lion Forge Guild</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	</head>
	<body class="is-preload">
		

			<nav id="nav">
				<ul class="container">
					<li><a href="/">Home</a></li>
                    <li class='dropdown-more'><a href="#" onclick="return false">FAQ/Guides</a>
                        <div class="dropdown-content">
							<a href="#">Crowfall FAQ</a>
							<a href="https://community.crowfall.com/topic/31367-lfg-beginners-guide-to-gathering/">Gathering Guide</a>
                            <a href="https://community.crowfall.com/topic/31368-lfg-beginners-guide-to-crafting/">Crafting Guide</a>                            
                        </div>
                    </li>
					<li><a href="#">RP Rules & Style Guides</a></li>
					<li><a href="#">Bazaar</a></li>
                    <li><a href="/recruitment/">Recruitment</a></li>
				</ul>
			</nav>

			<article id="top" class="wrapper style1">
				<div class="container opaque-container">
					<div class="row">
						<div class="col-4 col-5 col-12">
							<span class="image"><img src="images/LFG_Banner_1.png" alt="" /></span>
						</div>


						<!-- <div class="col-4 col-5-large col-12-medium">
							<span class="image"><img src="images/LFG_Banner_3.png" alt="" /></span>
						</div> -->
						<div class="col-12">
                            <form action="." method="post" id="crafting-request-form">
                                {% csrf_token %}
                                <fieldset class="col-12">
                                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}            
                                    <label for="requester" id="requester-label">Requester</label>
                                    <input type="text" name="requester" id="requester"><br><br>
                                    
                                    <label for="crafting_discipline" id="crafting-disc-label">Crafting discipline (note: selecting Blacksmithing will notify both Armorsmiths and Weaponsmiths)</label>
                                    <select name="crafting_discipline" id="crafting_discipline">
                                        <option value="ALC" name="ALC">Alchemy</option>
                                        <option value="ARM" name="ARM">Armorsmithing</option>
                                        <option value="BKS" name="BKS">Blacksmithing</option>
                                        <option value="CKG" name="CKG">Cooking</option>
                                        <option value="JWL" name="JWL">Jewelcrafting</option>
                                        <option value="LTW" name="LTW">Leatherworking</option>
                                        <!-- <option value="NEC" name="NEC" disabled>Necromancy</option> -->
                                        <option value="RUN" name="RUN">Runemaking</option>
                                        <!-- <option value="STO" name="STO" disabled>Stonemasonry</option> -->
                                        <option value="WPN" name="WPN">Weaponsmithing</option>
                                        <option value="WOO" name="WOO">Woodworking</option>
                                    </select><br>

                                    <label for="rarity" id="rarity-label">Rarity</label>
                                    <select name="rarity" id="rarity">
                                        <option selected></option>
                                        <option value="C">Common</option>
                                        <option value="U">Uncommon</option>
                                        <option value="R">Rare</option>
                                        <option value="E">Epic</option>
                                        <option value="L">Legendary</option>
                                    </select><br>
                                    
                                    <label for="item_name" id="item-name-label">Item name</label>
                                    <select id="item-selector">
                                        
                                    </select>                                    
                                    <input type="text" name="item_name" id="item_name" style="display:none"><br>
                                    
                                    <label for="quantity" id="quantity-label">Quantity</label>
                                    <input type="number" min="1" step="1" name="quantity" id="quantity"><br><br>                                    

                                    <label for="resource_provided">Can you provide materials?</label>
                                    <select name="resource_provided" id="resource_provided">
                                        <option value=0>No</option>
                                        <option value=1>Yes</option>
                                    </select><br>

                                    <div id="stats-div" class="hidden-craft-div">
                                        <label>Select stats</label>
                                        <textarea name="stats" id="stats" style="display:none"></textarea><br>
                                        <p id="stats-display"></p>
                                        <label for="stats" id='stats-labeler'>Select stats (put most important stats first)</label>
                                        <div id="stats-selector">                                        
                                            
                                        </div><br>                                        
                                    </div>
                                    
                                    <label for="special_instruction" >Special instruction (optional). 
                                        For example, max experimentation points on armor or use treated steel or use hunger shard, etc.
                                        If leaving to crafter's choice, give some context like "I'm a Vindicator".
                                    </label>
                                    <input type="text" name="special_instruction" id="special_instruction"><br>

                                    <label for="custom_name">Custom item name (optional, not always possible)</label>
                                    <input type="text" name="custom_name" id="custom_name"><br><br>

                                </fieldset>
                                <input type="button" value="Place order" id="validate">
                            </form>
                        </div>
					</div>
				</div>
				<ul id="copyright">
					<center><li style="color:#fff">&copy; Lion Forge Guild 2021. Made by Bearsy. All rights reserved.</li></center>					
				</ul>
			</article>
						
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
            <script src="{% static 'assets/js/addcraft.js' %}"></script>
	</body>
</html>

craftquests/templates/alliancecrafts/all.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>My test page</title>
    </head>
    <body>
    <h1>Active Claimed Requests</h1> 
    {% if claimed_req %}
        <ul>
        {% for item in claimed_req %}
            <li><a href="{% url 'getstatus' item.id %}">{{ item.requester }} [{{ item.crafting_discipline }}]: {{ item.quantity }}x{{ item.item_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No active requests.</p>
    {% endif %}
    
    <h1>Active Unclaimed Requests</h1> 
    {% if unclaimed_req %}
        <ul>
        {% for item in unclaimed_req %}
            <li><a href="{% url 'getstatus' item.id %}">{{ item.requester }} [{{ item.crafting_discipline }}]: {{ item.quantity }}x{{ item.item_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No active requests.</p>
    {% endif %}

    <h1>Completed Requests </h1> 
    {% if completed_req %}
        <ul>
        {% for item in completed_req %}
            <li><a href="{% url 'getstatus' item.id %}">{{ item.requester }} [{{ item.crafting_discipline }}]: {{ item.quantity }}x{{ item.item_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No completed requests.</p>
    {% endif %}
    <ul id="copyright">
        <center><li style="color:#fff">&copy; Lion Forge Guild 2021. Made by Bearsy. All rights reserved.</li></center>					
    </ul>
    
    </body>
</html>

craftquests/templates/alliancecrafts/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
    {% if req %}
        <ul>
            <h1>{{ req.get_status_display }} request</h1>

            <li>Requester: {{ req.requester }}</li>
            {% if req.crafter == None %}
              <li>Crafter: Not claimed yet </li>
            {% else %}
              <li>Crafter: {{ req.crafter }}</li>
            {% endif %}
            
            <li>Item: {{ req.get_rarity_display }} Quality, {{ req.item_name}} [{{ req.get_crafting_discipline_display }}]  </li>
            <li>Quantity: {{ req.quantity }} </li>
            <li>Materials provided? {{ req.get_resource_provided_display }} </li>
            <li>Custom naming: {{ req.custom_name}} </li>
            <li>Stats: {{ req.stats }}</li>            
        </ul>
        
    {% endif %}
    <ul id="copyright">
      <center><li style="color:#fff">&copy; Lion Forge Guild 2021. Made by Bearsy. All rights reserved.</li></center>					
    </ul>

  </body>
</html>